apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  config.js: |-
    window["_env_"] = {
      "NODE_ENV": "{{ .Values.app.node_env }}",
      "VITE_API_URL": "{{ .Values.app.api }}",
      "VITE_ANALYTICS_API_URL": "{{ .Values.app.analytics_api }}",
      "VITE_KEYCLOAK_URL": "{{ .Values.keycloak.url }}",
      "VITE_KEYCLOAK_CLIENT": "{{ .Values.keycloak.client }}",
      "VITE_KEYCLOAK_REALM": "{{ .Values.keycloak.realm }}",
      "VITE_REDASH_COMMENTS_PUBLIC_URL": "{{ .Values.redash.comments_public_url }}",
      "VITE_REDASH_PUBLIC_URL": "{{ .Values.redash.public_url }}",
      "VITE_PENGUIN_URL": "{{ .Values.penguin.url }}",
      "VITE_PENGUIN_ENABLED": "{{ .Values.penguin.enabled }}",
      "VITE_DEFAULT_TENANT": "{{ .Values.tenant.default_tenant }}",
      "VITE_IS_SINGLE_TENANT_ENVIRONMENT": "{{ .Values.tenant.is_single_tenant_environment }}",
      "VITE_CENTRE_API_URL": "{{ .Values.tenant.centre_api_url }}",
      "VITE_SITE_UPDATE_BANNER_ENABLED": "{{ (.Values.featureFlags | default dict).site_update_banner | default "false" }}"
    }
